### ISSUE TITLE
FR: Добавить возможность открывать не процесс, а файл с диска - для просмотра ExportList (интересуют DWARF символы и их адреса)

### ISSUE THREAD

**Issue by Alligator-1** [AlexanderBagel/ProcessMemoryMap#10]

**Comment by AlexanderBagel** [comment]
Так всё-таки ExportList или список функций которые присутствуют в DWARF? Экспорт и так виден в таблице экспорта и доступен без DWARF

**Comment by Alligator-1** [comment]
Мне порой нужно зная адрес - понять к какой функции он принадлежит
![изображение](https://github.com/user-attachments/assets/030deea1-2304-4513-8446-f13f404a2203)
И не всегда удобно запускать процесс для этого

Кстати, ещё что подумал - может быть есть возможность сделать тоже самое но для CallStack'а, т.е. если у меня есть CallStack из ProcessExplorer'а, чтобы можно было его загрузить при не запущенном процессе

**Comment by AlexanderBagel** [comment]
С колстеком так не получится. Нет нужной информации. А по поводу списка известных функций в DWARF/COFF по отдельному файлу с диска, подумаю, но это не скоро, не раньше осени. Сейчас другие задачи.

**Comment by AlexanderBagel** [comment]
https://github.com/AlexanderBagel/ProcessMemoryMap/tree/master/plugins/source/dwarfreader
