### ISSUE TITLE
Make initial window appear on the taskbar too

### ISSUE THREAD

**Issue by the-Arioch** [AlexanderBagel/ProcessMemoryMap#8]
Uncomfy...

The start is not instant. Also, when you compare two utilities run side by side.

You switch to other apps - then it is not obvious when PMM firsat window finally surfaces and is harder to switch to it.

![photo_2022-12-10_15-22-34](https://user-images.githubusercontent.com/937774/206854920-b7c1eebb-d4ff-4db4-8c82-c1fd29a62714.jpg)

**Comment by the-Arioch** [comment]
Maybe related - some GDI insection tools work poorly here.

![2022-12-10 15_29_19-Lister -  d__DelphiProjects_Apps_ProcessMemoryMap_uProcessMM dfm](https://user-images.githubusercontent.com/937774/206855175-f5deb35e-957f-459e-87eb-b8ace188c46c.png)

MS Spy++ 8.0.50727 manages to see it though (both find by picker and select in the GDI tree). However the cut of it i have lacks most features, so i can not test anything but "finding"

**Comment by Aynyuh** [comment]
@the-Arioch
In case it's still relevant for you please check the latest version. As I see the new version of PPM shows the "Select Process" window in the taskbar. There is also a new feature "Show Child Forms on TaskBar" to make all child windows visible in the taskbar according to the release note [v1.4.30-beta](https://github.com/AlexanderBagel/ProcessMemoryMap/releases/tag/v1.4.30-beta).
